### ISSUE TITLE
I can't merge your library with a working web server example

### ISSUE THREAD

**Issue by Serejka3** [ricardoquesada/esp-idf-arduino-bluepad32-template#12]
Your template and [this](https://github.com/ESP32Tutorials/ESP32-ESP-IDF-WebSocket-Web-Server-) example for simply webserver work separately for me.
But when I try to merge those two projects I have the problems. At first when I add include libraries in your template, several libraries requiries add it to CMakeLists.txt.
```
set(srcs
        "main.c"
        "sketch.cpp")

set(requires "bluepad32" "bluepad32_arduino" "arduino" "btstack")

idf_component_register(SRCS "${srcs}"
                    INCLUDE_DIRS "."
                    REQUIRES "${requires}" "esp_http_server" "spiffs" "esp_wifi")
```
OK, but with #include "connect_wifi.h" adding 
"esp_wifi" doesn't help.
`D:/Arduino/ESP32/ESP-IDF/robot8/main/main.c:31:10: fatal error: connect_wifi.h: No such file or directory
   31 | #include "connect_wifi.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.`
It seems the conflict with standard esp-idf libraries and arduino.
What am I doing wrong?

**Comment by ricardoquesada** [comment]
seems like it couldn't find `connect_wifi.h`... I haven't used that library, but it seems that you are adding "esp_wifi" as dependency... which looks Ok to me.

I wouldn't know... where did you add "esp_wifi" component ?
